version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - frontend:/app
    depends_on:
      - frontend

  frontend:
    build: .
    container_name: frontend
    ports:
      - 8080:8080
    volumes:
      - frontend:/app
    tty: true
        
volumes:
  frontend:

